# Generated by Django 4.2 on 2026-02-08 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memes', '0003_alter_meme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено модератором'),
        ),
        migrations.AddField(
            model_name='meme',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время модерации'),
        ),
        migrations.AddField(
            model_name='meme',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_memes', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='meme',
            name='moderation_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий модератора'),
        ),
        migrations.AddField(
            model_name='meme',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус модерации'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
