# Generated by Django 6.0.1

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_notification_report_alter_favorit...'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('meme_approved', 'Мем одобрен'), ('meme_rejected', 'Мем отклонен'), ('meme_reported', 'На ваш мем пожаловались'), ('report_resolved', 'Жалоба рассмотрена'), ('like', 'Лайк'), ('favorite', 'Добавление в избранное')], max_length=20),
        ),
    ]