# Generated by Django 4.2 on 2026-02-10 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memes', '0007_notification_link_alter_notification_related_meme'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('action_type', models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('register', 'Регистрация'), ('view_meme', 'Просмотр мема'), ('like_meme', 'Лайк мема'), ('unlike_meme', 'Убрал лайк'), ('favorite_meme', 'Добавил в избранное'), ('unfavorite_meme', 'Удалил из избранного'), ('add_meme', 'Добавил мем'), ('edit_meme', 'Редактировал мем'), ('delete_meme', 'Удалил мем'), ('report_meme', 'Пожаловался на мем'), ('search', 'Поиск'), ('view_profile', 'Просмотр профиля'), ('moderate', 'Модерация'), ('admin_action', 'Админ действие')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='memes.meme')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Активность пользователя',
                'verbose_name_plural': 'Активность пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'created_at'], name='memes_usera_user_id_abb0e3_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['action_type', 'created_at'], name='memes_usera_action__2463b6_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['ip_address', 'created_at'], name='memes_usera_ip_addr_8d48d0_idx'),
        ),
    ]
