# Generated by Django 4.2 on 2026-02-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0008_useractivity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
    ]
